CREATE TABLE Countries
(
Id INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR (50) UNIQUE NOT NULL
)

CREATE TABLE Customers
(
Id INT PRIMARY KEY IDENTITY,
FirstName NVARCHAR (25) NOT NULL,
LastName NVARCHAR (25) NOT NULL,
Gender CHAR(1) CHECK (Gender IN ('M','F')) NOT NULL,
Age INT NOT NULL,
PhoneNumber NVARCHAR (10) CHECK(LEN(PhoneNumber) = 10) NOT NULL,
CountryId INT NOT NULL FOREIGN KEY REFERENCES Countries(Id)
)

CREATE TABLE Products
(
Id INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR (25) UNIQUE NOT NULL,
[Description]  NVARCHAR (250) NULL,
Recipe NVARCHAR(MAX) NOT NULL,
Price DECIMAL (15,2) NOT NULL CHECK(Price >= 0)
)

CREATE TABLE Feedbacks
(
Id INT PRIMARY KEY IDENTITY,
[Description]  NVARCHAR (255) NULL,
Rate DECIMAL (4,2) CHECK(Rate BETWEEN 0 AND 10),
ProductId INT NOT NULL FOREIGN KEY REFERENCES Products(Id),
CustomerId INT NOT NULL FOREIGN KEY REFERENCES Customers(Id)
)

CREATE TABLE Distributors
(
Id INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR (25) NOT NULL,
AddressText  NVARCHAR (30) NOT NULL,
Summary NVARCHAR (200) NOT NULL,
CountryId INT NOT NULL FOREIGN KEY REFERENCES Countries(Id)
)

CREATE TABLE Ingredients
(
Id INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR (30) NOT NULL,
[Description]  NVARCHAR (200) NULL,
OriginCountryId INT NOT NULL FOREIGN KEY REFERENCES Countries(Id),
DistributorId INT NOT NULL FOREIGN KEY REFERENCES Distributors(Id)
)

CREATE TABLE ProductsIngredients
(
ProductId INT NOT NULL FOREIGN KEY REFERENCES Products(Id),
IngredientId INT NOT NULL FOREIGN KEY REFERENCES Ingredients(Id),
PRIMARY KEY (ProductId, IngredientId)
)