CREATE DATABASE ColonialJourney 

-- DDL

CREATE TABLE Planets
(
Id INT IDENTITY PRIMARY KEY,
[Name] VARCHAR (30) NOT NULL
)

CREATE TABLE Spaceports
(
Id INT IDENTITY PRIMARY KEY,
[Name] VARCHAR (50) NOT NULL,
PlanetId INT FOREIGN KEY REFERENCES Planets(Id)
)

CREATE TABLE Spaceships
(
Id INT IDENTITY PRIMARY KEY,
[Name] VARCHAR (50) NOT NULL,
Manufacturer VARCHAR (30) NOT NULL,
LightSpeedRate INT DEFAULT 0
)

CREATE TABLE Colonists
(
Id INT IDENTITY PRIMARY KEY,
FirstName  VARCHAR (20) NOT NULL,
LastName VARCHAR (20) NOT NULL,
Ucn VARCHAR (10) UNIQUE NOT NULL,
BirthDate DATE NOT NULL
)

CREATE TABLE Journeys
(
Id INT IDENTITY PRIMARY KEY,
JourneyStart DATETIME NOT NULL,
JourneyEnd DATETIME NOT NULL,
Purpose VARCHAR (11) UNIQUE CHECK (Purpose IN ('Medical','Technical','Educational','Military')) NOT NULL,
DestinationSpaceportId INT FOREIGN KEY REFERENCES Spaceports(Id),
SpaceshipId INT FOREIGN KEY REFERENCES Spaceships(Id),
)

CREATE TABLE TravelCards
(
Id INT IDENTITY PRIMARY KEY,
CardNumber VARCHAR (10) UNIQUE NOT NULL, 
JobDuringJourney VARCHAR (8) CHECK (JobDuringJourney IN ('Pilot','Engineer','Trooper','Cleaner','Cook')),
ColonistId INT FOREIGN KEY REFERENCES Colonists(Id) NOT NULL,
JourneyId INT FOREIGN KEY REFERENCES Journeys(Id) NOT NULL  
)