CREATE DATABASE OnlineStore
CREATE TABLE Cities
(
CityID INT PRIMARY KEY IDENTITY,
[Namr] VARCHAR (50) 
)

CREATE TABLE Customers
(
CustomerID INT IDENTITY PRIMARY KEY,
[Name] VARCHAR (50),
Birthday DATE,
CityID INT FOREIGN KEY REFERENCES Cities(CityID)
)

CREATE TABLE Orders
(
OrderID	INT PRIMARY KEY IDENTITY,
CustomerID INT FOREIGN KEY REFERENCES Customers (CustomerID)
)

CREATE TABLE ItemTypes
(

ItemTypeID INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50)
)

CREATE TABLE Items
(
ItemID INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50),
ItemTypeID INT FOREIGN KEY REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE OrderItems
(
OrderID INT ,
ItemID INT
CONSTRAINT PK_Order_Items PRIMARY KEY (OrderID, ItemID),
CONSTRAINT FK_Orders FOREIGN KEY(OrderID) REFERENCES Orders (OrderID),
CONSTRAINT FK_Items FOREIGN KEY (ItemID) REFERENCES Items(ItemID)
)

